version: '3.7'

services:

  mysql-master:
    image: mysql:8.0
    container_name: mysql-master
    command: --server-id=1 --log-bin=mysql-bin --binlog-format=row
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "8811:3306"
    networks:
      - mysql-replication
      
  mysql-slave1:
    image: mysql:8.0
    container_name: mysql-slave1
    command: --server-id=2 --log-bin=mysql-bin --binlog-format=row
    depends_on:
      - mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "8822:3306"
    networks:
      - mysql-replication

  mysql-slave2:
    image: mysql:8.0
    container_name: mysql-slave2
    command: --server-id=3 --log-bin=mysql-bin --binlog-format=row
    depends_on:
      - mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "8833:3306"
    networks:
      - mysql-replication
    
  mysql-exporter-master:
    image: prom/mysqld-exporter:latest
    command: --config.my-cnf=/cfg/.my.cnf
    container_name: mysql-exporter-master
    depends_on:
      - mysql-master
    ports:
      - "9104:9104"
    volumes:
      - "./config.my-cnf:/cfg/.my.cnf"
    networks:
      - mysql-replication

  mysql-exporter-slave1:
    image: prom/mysqld-exporter:latest
    command: --config.my-cnf=/cfg/.my.cnf
    container_name: mysql-exporter-slave1
    depends_on:
      - mysql-slave1
    ports:
      - "9105:9104"
    volumes:
      - "./config.my-slave1-cnf:/cfg/.my.cnf"
    networks:
      - mysql-replication
      
  mysql-exporter-slave2:
    image: prom/mysqld-exporter:latest
    command: --config.my-cnf=/cfg/.my.cnf
    container_name: mysql-exporter-slave2
    depends_on:
      - mysql-slave2
    ports:
      - "9106:9104"
    volumes:
      - "./config.my-slave2-cnf:/cfg/.my.cnf"
    networks:
      - mysql-replication

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - mysql-replication

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - mysql-replication

networks:
    mysql-replication:

volumes:
  grafana-storage:
